name: Code Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx || true

      - name: Build React App
        run: npm run build
