name: Code Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx

      - name: Build React App
        run: npm run build
